### ISSUE TITLE
[Sign up] - 2nd password entry

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#118]
On signing up, the second password entry always says '**Your passwords match!**' even though they don't.
When they don't match and you click 'Next' it will not show that the 2nd password is incorrect and returns step 1 with no visible error.

This is especially confusing if the 2nd password has the same length as the first but includes another character.

**Comment by guysoft** [comment]
Hey, this issue is still online on the website, has https://github.com/BeWelcome/rox/commit/8a049843ac57e9535a28eff7e9a97f78dcbd01b0 been pulled in to https://www.bewelcome.org ?
Image from today
![Screenshot_20200516_224942](https://user-images.githubusercontent.com/325670/82128982-395ef800-97c8-11ea-9b22-4193fd83ea01.png)

**Comment by thisismeonmounteverest** [comment]
Hey guysoft,

Updated code is first deployed to beta.bewelcome.org and when tested there brought to www.

So no, this hasn't been pulled to www yet.
