### ISSUE TITLE
Link to group in email notification

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#15]
An email notification of a message within a group should be accompanied by a direct link to the group (and/or message)

**Comment by thisismeonmounteverest** [comment]
This link is there in the HTML notification but is missing in case of the text only notification.

**Comment by jhodgdon-drp** [comment]
Hah! I was just thinking about reporting this issue, but looked at the list of open issues first and found this one. :) 

I would suggest including a link to the message, rather than the group (or as a priority over including a link, to the group). Today when I was trying to find the Alpha Preview message from the Testing group, without the link being in the email message, it took me a lot of clicks. Other forum sites where I have subscriptions, there's a direct link to the message -- that seems to be the norm among other forum software.

(By the way I am "HodgBlog" on BeWelcome, and a member of the testing group.)

**Comment by thisismeonmounteverest** [comment]
@Jennifer: Did you set your mail preference to mail only?

**Comment by jhodgdon-drp** [comment]
Um. I think you are asking about the mail formatting preference? Yes, I have it set to "MarkDown Only" instead of HTML mail format.

**Comment by thisismeonmounteverest** [comment]
Fixed by adding the title information to the body text.
