### ISSUE TITLE
search in discussions of groups

### ISSUE THREAD

**Issue by HDValentin** [BeWelcome/rox#198]
Feature request:
I would like to have a full text search in groups.

Some years ago I posted a feature request at bewelcome.org and I cant find it by clicking through the 25 Sites of Feature requests.
A search field is missing

**Comment by thisismeonmounteverest** [comment]
@HDValentin I agree we should be able to search only in a group.

As a work around use the one on the top of this page: https://www.bewelcome.org/forums

**Comment by HDValentin** [comment]
Yes this helps, thank you. To have this field in Groups would be a great enhancement.

**Comment by subacultured** [comment]
Seems to work but does throw up threads within keyword. Hard to judge accuracy scientifically. 

e.g T-Shirt - seems very accurate, but some threads without keyword
Berlin - seems accurate
app - accurate, but not doesn't pick up with phrases like native app

**Comment by crumbking** [comment]
Works like a charm for me. 
@subacultured 
I can't really see the issue here both show valid results:

https://www.bewelcome.org/group/2794/search?fs-keyword=app
https://www.bewelcome.org/group/2794/search?fs-keyword=native+app

Therefore close as introduced with last release. New requirements go into a follow up.
