### ISSUE TITLE
[feedback] Add a captcha to the public form

### ISSUE THREAD

**Issue by crumbking** [BeWelcome/rox#225]
To avoid spam for our support volunteers we should set at least for the public form a captcha or somthing similar.

Maybe https://github.com/Gregwar/CaptchaBundle could be an option for the public form.

Google free and not connected to third party provider would be good.

**Comment by crumbking** [comment]
Tested on beta without login. Thought I needed 3 attempts to submit. Hard to read sometimes but that's good ;-)

**Comment by gbenouville** [comment]
I also tested and it worked fine (no problem to read it). Just maybe change the label: the usual thing for a captcha is something like "please copy the following text in order to check you're not a robot", instead of just "captcha".

I had read somewhere that text captcha were going to be discontinued (replaced by pictures), but actually they'll remain usable?

**Comment by crumbking** [comment]
Fixed with last release.
