### ISSUE TITLE
Zooming in too much in the map returns the world map

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#83]
If I zoom in and zoom in further, a clear world map is shown

**Comment by thisismeonmounteverest** [comment]
Which browser? Did you wait for the map to be updated?

**Comment by nekekala** [comment]
Hi people,
i didn't open a new thread since i encountered an error when i try to zoom in the map (and this thread seemed similar), seems that with my attempt to zoom in the world map under "Find Members" (https://alpha.bewelcome.org/search/members) the page breaks (and the Show map button unticks) and shows me this message:
 'Error' This form should not contain extra fields.

it seems that i can click on show map button and get back part of the map but the problem insists when i try to interact with the map again. 
 
 btw the pages crashes either on zoom on the map or in drag the map to another location
 
I tried it on Firefox Quantum 63.0.3 (x64) in Windows 10 and here is a screenshot of before and after:

![1](https://user-images.githubusercontent.com/24875951/49436045-beb34000-f7c0-11e8-931a-ecf6e497d2b7.JPG)
![2](https://user-images.githubusercontent.com/24875951/49436049-c1159a00-f7c0-11e8-99d0-76b1159e12ae.JPG)

**Comment by thisismeonmounteverest** [comment]
@nekekala Thanks for adding to this issue.

The 'Show map' should stay active even if the map is changed (dragged or zoomed).

**Comment by thisismeonmounteverest** [comment]
@nekekala: The extra fields error message should be fixed. Zooming in and dragging won't reload the page for now to avoid the reported issues.

**Comment by amnesiac84** [comment]
Seems to be fixed now
